export const treeData = {
  name: 'hpe',
  oid: '1.3.6.1.4.1.47196',
  class: 'objectidentity',
  children: [
    {
      name: 'hpeNetworking',
      oid: '1.3.6.1.4.1.47196.4',
      class: 'moduleidentity',
      description:
        'esto es un test aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa aaaaaaaaaa',
      children: [
        {
          name: 'reservedhpeNetworking',
          oid: '1.3.6.1.4.1.47196.4.0',
          class: 'objectidentity',
          children: [],
        },
        {
          name: 'wiredNetworkingDevices',
          oid: '1.3.6.1.4.1.47196.4.1',
          class: 'objectidentity',
          children: [
            {
              name: 'arubaOS_CX',
              oid: '1.3.6.1.4.1.47196.4.1.1',
              class: 'objectidentity',
              children: [
                {
                  name: 'wndDeviceIds',
                  oid: '1.3.6.1.4.1.47196.4.1.1.1',
                  class: 'objectidentity',
                  children: [
                    {
                      name: 'arubaWiredSwitchJL375A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.1',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL479A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.2',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL579A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.3',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL581A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.5',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL635A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.50',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL636A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.70',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL658A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.100',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL659A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.101',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL660A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.102',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL661A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.103',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL662A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.104',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL663A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.105',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL664A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.106',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL665A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.107',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL666A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.108',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL667A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.109',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL668A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.110',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL762A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.111',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchR0X24A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.150',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchR0X25A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.151',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL724A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.300',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL725A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.301',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL726A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.302',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL727A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.303',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredSwitchJL728A',
                      oid: '1.3.6.1.4.1.47196.4.1.1.1.304',
                      class: 'objectidentity',
                      children: [],
                    },
                  ],
                },
                {
                  name: 'wndComponentIds',
                  oid: '1.3.6.1.4.1.47196.4.1.1.2',
                  class: 'objectidentity',
                  children: [
                    {
                      name: 'wndSensors',
                      oid: '1.3.6.1.4.1.47196.4.1.1.2.1',
                      class: 'objectidentity',
                      children: [
                        {
                          name: 'arubaWiredTemperatureSensor',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.1.1',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredRPMSensor',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.1.2',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredPowerSensor',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.1.3',
                          class: 'objectidentity',
                          children: [],
                        },
                      ],
                    },
                    {
                      name: 'wndSlots',
                      oid: '1.3.6.1.4.1.47196.4.1.1.2.2',
                      class: 'objectidentity',
                      children: [
                        {
                          name: 'arubaWiredSwitch8400FanTraySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.1',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8400PowerSupplySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.2',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8400ManagementModuleSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.3',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8400LineCardSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.4',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8400FabricCardSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.5',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8400RearDisplayCardSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.6',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8320FanTraySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.7',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8320PowerSupplySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.8',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8325FanTraySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.9',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch8325PowerSupplySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.10',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6300FanTraySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.11',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6300PowerSupplySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.12',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6400ManagementModuleSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.13',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6400LineCardSlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.14',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6400FanTraySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.15',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch6400PowerSupplySlot',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.2.16',
                          class: 'objectidentity',
                          children: [],
                        },
                      ],
                    },
                    {
                      name: 'wndModules',
                      oid: '1.3.6.1.4.1.47196.4.1.1.2.3',
                      class: 'objectidentity',
                      children: [
                        {
                          name: 'arubaWiredSwitchManagementModuleJL368A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.1',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL363A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.2',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL365A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.3',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL366A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.4',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFabricModuleJL367A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.5',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanModuleJL370A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.6',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL372A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.7',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchJL369AFanTray',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.8',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL479A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.9',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL480A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.10',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchJL481AFanTray',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.11',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchRearDisplayModule8400',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.12',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch1GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.13',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch10GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.14',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch25GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.15',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch40GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.16',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch100GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.17',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchSmartRatePort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.18',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL579A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.19',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL581A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.20',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL635A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.21',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL624A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.22',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL625A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.23',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL636A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.24',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL626A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.25',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL627A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.26',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL632A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.27',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL633A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.28',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL628A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.29',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL629A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.30',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL630A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.31',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL631A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.32',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL658A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.33',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL659A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.34',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL660A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.35',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL661A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.36',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL662A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.37',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL663A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.38',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL664A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.39',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL665A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.40',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL666A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.41',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL667A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.42',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL668A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.43',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL669A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.44',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL085A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.45',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL086A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.46',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL087A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.47',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL670A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.48',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL687A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.350',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitch50GbMaxPort',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.50',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X31A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.51',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X32A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.52',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X33A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.53',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X34A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.54',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X35A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.55',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X36A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.56',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X37A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.57',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X38A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.58',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X39A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.59',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X40A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.60',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X41A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.61',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X42A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.62',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X43A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.63',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X44A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.64',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X45A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.65',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL762A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.70',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchFanTrayJL761A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.71',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchPowerSupplyUnitJL760A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.72',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL724A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.90',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL725A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.91',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL726A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.92',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL727A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.93',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchModuleJL728A',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.94',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X38B',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.103',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X39B',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.104',
                          class: 'objectidentity',
                          children: [],
                        },
                        {
                          name: 'arubaWiredSwitchR0X40B',
                          oid: '1.3.6.1.4.1.47196.4.1.1.2.3.105',
                          class: 'objectidentity',
                          children: [],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: 'wndFeatures',
                  oid: '1.3.6.1.4.1.47196.4.1.1.3',
                  class: 'objectidentity',
                  children: [
                    {
                      name: 'arubaWiredLoopProtectMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.1',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredMclagMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.2',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredMgmdSnoopingMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.3',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredMgmdRmonTrapMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.4',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredRpvstMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.5',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredMvrpMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.6',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredVsxMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.7',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredPoeMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.8',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredLldpMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.9',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredVsfMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.10',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredChassisMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.11',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredCiptMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.12',
                      class: 'objectidentity',
                      children: [],
                    },
                    {
                      name: 'arubaWiredMstpMIB',
                      oid: '1.3.6.1.4.1.47196.4.1.1.3.13',
                      class: 'objectidentity',
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
